#ifndef NC_DATA_H_INCLUDED
#define NC_DATA_H_INCLUDED

#define NC_VOTER_VARCHARS char county_desc[17], ncid[14], last_name[27], first_name[22], middle_name[22], name_suffix_lbl[5], status_cd[4], voter_status_desc[27], reason_cd[4], voter_status_reason_desc[62], voter_reg_num[14], res_street_address[67], res_city_desc[62], state_cd[4], zip_code[11], mail_addr1[42], mail_addr2[42], mail_addr3[42], mail_addr4[42], mail_city[32], mail_state[4], mail_zipcode[11], full_phone_number[14], confidential_ind[3], registr_dt[12], race_code[5], ethnic_code[5], party_cd[5], gender_code[3], birth_year[6], age_at_year_end[5], birth_state[4], drivers_lic[3], precinct_abbrv[8], municipality_abbrv[8], ward_abbrv[8], cong_dist_abbrv[8], super_court_abbrv[8], judic_dist_abbrv[8], nc_senate_abbrv[8], nc_house_abbrv[8], county_commiss_abbrv[8], township_abbrv[8], school_dist_abbrv[8], fire_dist_abbrv[8], water_dist_abbrv[8], sewer_dist_abbrv[8], sanit_dist_abbrv[8], rescue_dist_abbrv[8], munic_dist_abbrv[8], dist_1_abbrv[8], vtd_abbrv[8], vtd_desc[62], dist_1_desc[62], munic_dist_desc[62], rescue_dist_desc[62], sanit_dist_desc[62], sewer_dist_desc[62], water_dist_desc[62], fire_dist_desc[62], school_dist_desc[62], township_desc[62], county_commiss_desc[62], ward_desc[62], municipality_desc[62], precinct_desc[62];

#define NC_VOTER_VARCHARS_INIT char county_desc[17] = { '\0' }, ncid[14] = { '\0' }, last_name[27] = { '\0' }, first_name[22] = { '\0' }, middle_name[22] = { '\0' }, name_suffix_lbl[5] = { '\0' }, status_cd[4] = { '\0' }, voter_status_desc[27] = { '\0' }, reason_cd[4] = { '\0' }, voter_status_reason_desc[62] = { '\0' }, voter_reg_num[14] = { '\0' }, res_street_address[67] = { '\0' }, res_city_desc[62] = { '\0' }, state_cd[4] = { '\0' }, zip_code[11] = { '\0' }, mail_addr1[42] = { '\0' }, mail_addr2[42] = { '\0' }, mail_addr3[42] = { '\0' }, mail_addr4[42] = { '\0' }, mail_city[32] = { '\0' }, mail_state[4] = { '\0' }, mail_zipcode[11] = { '\0' }, full_phone_number[14] = { '\0' }, confidential_ind[3] = { '\0' }, registr_dt[12] = { '\0' }, race_code[5] = { '\0' }, ethnic_code[5] = { '\0' }, party_cd[5] = { '\0' }, gender_code[3] = { '\0' }, birth_year[6] = { '\0' }, age_at_year_end[5] = { '\0' }, birth_state[4] = { '\0' }, drivers_lic[3] = { '\0' }, precinct_abbrv[8] = { '\0' }, municipality_abbrv[8] = { '\0' }, ward_abbrv[8] = { '\0' }, cong_dist_abbrv[8] = { '\0' }, super_court_abbrv[8] = { '\0' }, judic_dist_abbrv[8] = { '\0' }, nc_senate_abbrv[8] = { '\0' }, nc_house_abbrv[8] = { '\0' }, county_commiss_abbrv[8] = { '\0' }, township_abbrv[8] = { '\0' }, school_dist_abbrv[8] = { '\0' }, fire_dist_abbrv[8] = { '\0' }, water_dist_abbrv[8] = { '\0' }, sewer_dist_abbrv[8] = { '\0' }, sanit_dist_abbrv[8] = { '\0' }, rescue_dist_abbrv[8] = { '\0' }, munic_dist_abbrv[8] = { '\0' }, dist_1_abbrv[8] = { '\0' }, vtd_abbrv[8] = { '\0' }, vtd_desc[62] = { '\0' }, dist_1_desc[62] = { '\0' }, munic_dist_desc[62] = { '\0' }, rescue_dist_desc[62] = { '\0' }, sanit_dist_desc[62] = { '\0' }, sewer_dist_desc[62] = { '\0' }, water_dist_desc[62] = { '\0' }, fire_dist_desc[62] = { '\0' }, school_dist_desc[62] = { '\0' }, township_desc[62] = { '\0' }, county_commiss_desc[62] = { '\0' }, ward_desc[62] = { '\0' }, municipality_desc[62] = { '\0' }, precinct_desc[62] = { '\0' }; 

#define NC_VOTER_VARCHARS_FIELD_LIST(STRUCTNAME) (STRUCTNAME).county_desc, (STRUCTNAME).voter_reg_num, (STRUCTNAME).ncid, (STRUCTNAME).last_name, (STRUCTNAME).first_name, (STRUCTNAME).middle_name, (STRUCTNAME).name_suffix_lbl, (STRUCTNAME).status_cd, (STRUCTNAME).voter_status_desc, (STRUCTNAME).reason_cd, (STRUCTNAME).voter_status_reason_desc, (STRUCTNAME).res_street_address, (STRUCTNAME).res_city_desc, (STRUCTNAME).state_cd, (STRUCTNAME).zip_code, (STRUCTNAME).mail_addr1, (STRUCTNAME).mail_addr2, (STRUCTNAME).mail_addr3, (STRUCTNAME).mail_addr4, (STRUCTNAME).mail_city, (STRUCTNAME).mail_state, (STRUCTNAME).mail_zipcode, (STRUCTNAME).full_phone_number, (STRUCTNAME).confidential_ind, (STRUCTNAME).registr_dt, (STRUCTNAME).race_code, (STRUCTNAME).ethnic_code, (STRUCTNAME).party_cd, (STRUCTNAME).gender_code, (STRUCTNAME).birth_year, (STRUCTNAME).age_at_year_end, (STRUCTNAME).birth_state, (STRUCTNAME).drivers_lic, (STRUCTNAME).precinct_abbrv, (STRUCTNAME).precinct_desc, (STRUCTNAME).municipality_abbrv, (STRUCTNAME).municipality_desc, (STRUCTNAME).ward_abbrv, (STRUCTNAME).ward_desc, (STRUCTNAME).cong_dist_abbrv, (STRUCTNAME).super_court_abbrv, (STRUCTNAME).judic_dist_abbrv, (STRUCTNAME).nc_senate_abbrv, (STRUCTNAME).nc_house_abbrv, (STRUCTNAME).county_commiss_abbrv, (STRUCTNAME).county_commiss_desc, (STRUCTNAME).township_abbrv, (STRUCTNAME).township_desc, (STRUCTNAME).school_dist_abbrv, (STRUCTNAME).school_dist_desc, (STRUCTNAME).fire_dist_abbrv, (STRUCTNAME).fire_dist_desc, (STRUCTNAME).water_dist_abbrv, (STRUCTNAME).water_dist_desc, (STRUCTNAME).sewer_dist_abbrv, (STRUCTNAME).sewer_dist_desc, (STRUCTNAME).sanit_dist_abbrv, (STRUCTNAME).sanit_dist_desc, (STRUCTNAME).rescue_dist_abbrv, (STRUCTNAME).rescue_dist_desc, (STRUCTNAME).munic_dist_abbrv, (STRUCTNAME).munic_dist_desc, (STRUCTNAME).dist_1_abbrv, (STRUCTNAME).dist_1_desc, (STRUCTNAME).vtd_abbrv, (STRUCTNAME).vtd_desc

#define NC_VOTER_FIELD_LIST(STRUCTNAME) &STRUCTNAME.county_id, NC_VOTER_VARCHARS_FIELD_LIST(STRUCTNAME)

#define NC_VOTER_SQL_VARCHAR_PARAMS_LIST ":county_desc", ":voter_reg_num", ":ncid", ":last_name", ":first_name", ":middle_name", ":name_suffix_lbl", ":status_cd", ":voter_status_desc", ":reason_cd", ":voter_status_reason_desc", ":res_street_address", ":res_city_desc", ":state_cd", ":zip_code", ":mail_addr1", ":mail_addr2", ":mail_addr3", ":mail_addr4", ":mail_city", ":mail_state", ":mail_zipcode", ":full_phone_number", ":confidential_ind", ":registr_dt", ":race_code", ":ethnic_code", ":party_cd", ":gender_code", ":birth_year", ":age_at_year_end", ":birth_state", ":drivers_lic", ":precinct_abbrv", ":precinct_desc", ":municipality_abbrv", ":municipality_desc", ":ward_abbrv", ":ward_desc", ":cong_dist_abbrv", ":super_court_abbrv", ":judic_dist_abbrv", ":nc_senate_abbrv", ":nc_house_abbrv", ":county_commiss_abbrv", ":county_commiss_desc", ":township_abbrv", ":township_desc", ":school_dist_abbrv", ":school_dist_desc", ":fire_dist_abbrv", ":fire_dist_desc", ":water_dist_abbrv", ":water_dist_desc", ":sewer_dist_abbrv", ":sewer_dist_desc", ":sanit_dist_abbrv", ":sanit_dist_desc", ":rescue_dist_abbrv", ":rescue_dist_desc", ":munic_dist_abbrv", ":munic_dist_desc", ":dist_1_abbrv", ":dist_1_desc", ":vtd_abbrv", ":vtd_desc"

#define NC_VOTER_FIELDS int county_id; NC_VOTER_VARCHARS
#define NC_VOTER_FIELD_INIT int county_id = 0; NC_VOTER_VARCHARS_INIT

struct nc_voter_data {
    NC_VOTER_FIELDS
};
#endif
